Name: Bryan Sandor

Course: STAT 558

Title: Project 2

# Preamble

The following code may be used to reload a module.

In [25]:
# import importlib
# importlib.reload(Name_of_module)

# Part I - Creating a Class

First we import all the necessary libraries and initiate a spark session.

In [26]:
from pyspark.sql import DataFrame
from pyspark.sql import functions as F
from functools import reduce
from pyspark.sql.types import *
import pandas as pd

from pyspark.sql import SparkSession
spark = SparkSession.builder \
        .appName("proj2") \
        .config("spark.sql.ansi.enabled", "false") \
        .getOrCreate()

In [27]:
import proj2class

In [96]:
testdat = pd.DataFrame({"Number": [7, 1], "Jersey": ["9", "3"],
                        "Name": ["Bob", "George"], "Lucky": [2.71828182, 3.1415926535897932386433],
                        "Non-term": [1 / 3, 2 ** (1/2)], "Validity": [True, False]},
                        index = [5, 3])
testdat

   Number Jersey    Name     Lucky  Non-term  Validity
5       7      9     Bob  2.718282  0.333333      True
3       1      3  George  3.141593  1.414214     False

In [101]:
sparktestdat = spark.createDataFrame(testdat)
sparktestdat.show()

+------+------+------+-----------------+------------------+--------+
|Number|Jersey|  Name|            Lucky|          Non-term|Validity|
+------+------+------+-----------------+------------------+--------+
|     7|     9|   Bob|       2.71828182|0.3333333333333333|    true|
|     1|     3|George|3.141592653589793|1.4142135623730951|   false|
+------+------+------+-----------------+------------------+--------+

In [98]:
sparktestdat2 = proj2class.SparkDataCheck.makepdf(spark, testdat)
sparktestdat2

In [99]:
sparktestdat3 = proj2class.SparkDataCheck.makespark(spark, "AirQualityUCI.csv", delimiter = ';')
sparktestdat3

In [102]:
sparktestdat.dtypes

[('Number', 'bigint'),
 ('Jersey', 'string'),
 ('Name', 'string'),
 ('Lucky', 'double'),
 ('Non-term', 'double'),
 ('Validity', 'boolean')]

In [141]:
import importlib
importlib.reload(proj2class)

In [149]:
testdat.assign(Result = testdat.Number.between(1, 7))

   Number Jersey    Name     Lucky  Non-term  Validity  Result
5       7      9     Bob  2.718282  0.333333      True    True
3       1      3  George  3.141593  1.414214     False    True

In [150]:
testdat

   Number Jersey    Name     Lucky  Non-term  Validity
5       7      9     Bob  2.718282  0.333333      True
3       1      3  George  3.141593  1.414214     False

In [142]:
proj2class.SparkDataCheck.threshold(column = testdat.Number, lower = 1, upper = 5)

AttributeError: 'Series' object has no attribute 'append'