Name: Bryan Sandor

Course: STAT 558

Title: Project 2

# Preamble

The following code may be used to reload a module.

In [1]:
# importlib.reload(Name_of_module)

# Part I - Creating a Class

First we import all the necessary libraries and initiate a spark session.

In [2]:
from pyspark.sql import DataFrame
from pyspark.sql import functions as F
from functools import reduce
from pyspark.sql.types import *
import pandas as pd
import importlib # used with importlib.reload(Name_of_Module) to reload module

from pyspark.sql import SparkSession
spark = SparkSession.builder \
        .appName("proj2") \
        .config("spark.sql.ansi.enabled", "false") \
        .getOrCreate()

WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/03/25 21:27:39 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

In [3]:
import proj2class

In [4]:
import numpy as np
testdat = pd.DataFrame({"Number": [7, 1, np.nan], "Jersey": ["9", "3", "99"],
                        "Name": ["Bob", np.nan, "Fred"],
                        "Lucky": [2.7182818284590452, 3.1415926535897932, 1.6180339887498948],
                        "Non-term": [2 / 3, 2 ** (1/2), (-2) ** 11],
                        "Validity": [True, False, False]},
                        index = [5, 3, -1])
testdat

    Number Jersey  Name     Lucky     Non-term  Validity
 5     7.0      9   Bob  2.718282     0.666667      True
 3     1.0      3   NaN  3.141593     1.414214     False
-1     NaN     99  Fred  1.618034 -2048.000000     False

In [5]:
sparktestdat = spark.createDataFrame(testdat)
sparktestdat.show()

+------+------+----+-----------------+------------------+--------+
|Number|Jersey|Name|            Lucky|          Non-term|Validity|
+------+------+----+-----------------+------------------+--------+
|   7.0|     9| Bob|2.718281828459045|0.6666666666666666|    true|
|   1.0|     3| NaN|3.141592653589793|1.4142135623730951|   false|
|   NaN|    99|Fred|1.618033988749895|           -2048.0|   false|
+------+------+----+-----------------+------------------+--------+

In [6]:
sparktestdat2 = proj2class.SparkDataCheck.makespark(spark, "AirQualityUCI.csv", delimiter = ';')
sparktestdat2

In [7]:
sparktestdat3 = pd.read_csv("AirQualityUCI.csv", sep = ';')
sparktestdat3.head()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Unnamed: 15,Unnamed: 16
0,10/03/2004,18.00.00,"2,6",1360.0,150.0,"11,9",1046.0,166.0,1056.0,113.0,1692.0,1268.0,"13,6","48,9","0,7578",NaN,NaN
1,10/03/2004,19.00.00,2,1292.0,112.0,"9,4",955.0,103.0,1174.0,92.0,1559.0,972.0,"13,3","47,7","0,7255",NaN,NaN
2,10/03/2004,20.00.00,"2,2",1402.0,88.0,"9,0",939.0,131.0,1140.0,114.0,1555.0,1074.0,"11,9","54,0","0,7502",NaN,NaN
3,10/03/2004,21.00.00,"2,2",1376.0,80.0,"9,2",948.0,172.0,1092.0,122.0,1584.0,1203.0,"11,0","60,0","0,7867",NaN,NaN
4,10/03/2004,22.00.00,"1,6",1272.0,51.0,"6,5",836.0,131.0,1205.0,116.0,1490.0,1110.0,"11,2","59,6","0,7888",NaN,NaN

In [8]:
sparktestdat4 = spark.createDataFrame(sparktestdat3)
sparktestdat4.show(5)

+----------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-----------+-----------+
|      Date|    Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|Unnamed: 15|Unnamed: 16|
+----------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-----------+-----------+
|10/03/2004|18.00.00|   2,6|     1360.0|   150.0|    11,9|       1046.0|  166.0|      1056.0|  113.0|      1692.0|     1268.0|13,6|48,9|0,7578|        NaN|        NaN|
|10/03/2004|19.00.00|     2|     1292.0|   112.0|     9,4|        955.0|  103.0|      1174.0|   92.0|      1559.0|      972.0|13,3|47,7|0,7255|        NaN|        NaN|
|10/03/2004|20.00.00|   2,2|     1402.0|    88.0|     9,0|        939.0|  131.0|      1140.0|  114.0|      1555.0|     1074.0|11,9|54,0|0,7502|        NaN|        NaN|
|10/03/2004|21.00.00|   2,2|     1376.0|    80.0|     9,2|        948.0|  172.0|      1092.0|  122.0|      1584.0|     1203.0|11,0|60,0|0,7867|        NaN|        NaN|
|10/03/2004|22.00.00|   1,6|     1272.0|    51.0|     6,5|        836.0|  131.0|      1205.0|  116.0|      1490.0|     1110.0|11,2|59,6|0,7888|        NaN|        NaN|
+----------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-----------+-----------+
only showing top 5 rows

In [9]:
proj2class.SparkDataCheck.nulrange(testdat, "Name")

    Number Jersey  Name     Lucky     Non-term  Validity  Result
 5     7.0      9   Bob  2.718282     0.666667      True   False
 3     1.0      3   NaN  3.141593     1.414214     False    True
-1     NaN     99  Fred  1.618034 -2048.000000     False   False

In [10]:
proj2class.SparkDataCheck.nulrange(sparktestdat3, "Unnamed: 15")

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Unnamed: 15,Unnamed: 16,Result
0,10/03/2004,18.00.00,"2,6",1360.0,150.0,"11,9",1046.0,166.0,1056.0,113.0,1692.0,1268.0,"13,6","48,9","0,7578",NaN,NaN,True
1,10/03/2004,19.00.00,2,1292.0,112.0,"9,4",955.0,103.0,1174.0,92.0,1559.0,972.0,"13,3","47,7","0,7255",NaN,NaN,True
2,10/03/2004,20.00.00,"2,2",1402.0,88.0,"9,0",939.0,131.0,1140.0,114.0,1555.0,1074.0,"11,9","54,0","0,7502",NaN,NaN,True
3,10/03/2004,21.00.00,"2,2",1376.0,80.0,"9,2",948.0,172.0,1092.0,122.0,1584.0,1203.0,"11,0","60,0","0,7867",NaN,NaN,True
4,10/03/2004,22.00.00,"1,6",1272.0,51.0,"6,5",836.0,131.0,1205.0,116.0,1490.0,1110.0,"11,2","59,6","0,7888",NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9466,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
9467,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
9468,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
9469,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
9470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True

In [11]:
importlib.reload(proj2class)

In [12]:
min([1,3,5])

1

In [13]:
max([1,3,5])

5

In [18]:
sparktestdat4.select(F.max("CO(GT)")).show()

+-----------+
|max(CO(GT))|
+-----------+
|        NaN|
+-----------+